/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.jtrs;

public class JTetris {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new JTetris().getGreeting());
    }
}
