/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.jtrs;

import it.unibo.jtrs.controller.impl.ApplicationImpl;

public class JTetris {

    private JTetris() {}

    public static void main(String[] args) {
        new ApplicationImpl();
    }
}
