/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.jtrs;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class JTetrisTest {
    @Test void appHasAGreeting() {
        JTetrisTest classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
